name: Generate Snake

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Generate the snake SVG
        uses: Platane/snk@v3.2.0 # Replace with the correct version number.
        with:
          # Make sure these options are correct according to the action's documentation
          github_user_name: ${{ github.repository_owner }}
          # Define the outputs based on the action's documentation
          # If these are incorrect, you'll need to replace them with the correct ones
          # ...

      - name: Commit and push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output # Ensure this is the branch you want to push to
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
